### ISSUE TITLE
Spinning circle indefinitely

### ISSUE THREAD

**Issue by aspopovic** [ejasso112/questland-optimizer#1]
Thundersoap changed api recently, so the site doesn't load properly - spinning circle keeps spinning. Please ask for new api key and fix this asap, because we do use this site...

**Comment by ejasso112** [comment]
> Thundersoap changed api recently, so the site doesn't load properly - spinning circle keeps spinning. Please ask for new api key and fix this asap, because we do use this site...

Thanks for letting me know, I’ll try and have it fixed before tomorrow.

**Comment by ejasso112** [comment]
This issue has now been fixed, thanks for notifying of the problem.
