### ISSUE TITLE
Questland Public API Integration

### ISSUE THREAD

**Issue by sbennett18** [ejasso112/questland-optimizer#2]
I see that the you are already using the Questland API to get all the gear data -- have you considered using the hero-endpoint to optionally fill in the gear data automatically?
I was playing around with a Python optimizer until I found this one online and think that would make a great addition.

**Comment by ejasso112** [comment]
Ive actually been working to integrate that to a newer version of the site that is still a work in progress. It wont be done until another couple of days since im pretty busy.

**Comment by sbennett18** [comment]
Fair enough! Let me know if there's anything I can do to help, otherwise I'll close this issue once you release the new version of the site. Cheers!

**Comment by ejasso112** [comment]
Hey sorry for the wait. I'm here to let you know that I finished updating the website. I made a new repository for it so if you want to check it out here's the link: https://github.com/ejasso112/questland-optimizer-v2.

**Comment by sbennett18** [comment]
That's excellent! Just tried it out and it looks really nice and works exactly as I hoped it would, allowing to load and modify/play around with manually. Thanks so much for your efforts!
